import { Injectable } from '@nestjs/common';
import { PrismaService } from '../../prisma/prisma.service';
import { TransferStatus } from '../../generated/prisma/enums';

// ── Types ─────────────────────────────────────────────────────────────────────

/** Full transfer record as returned by Prisma (no relations). */
export type TicketTransferRecord = {
  id: string;
  ticketId: string;
  senderId: string;
  recipientEmail: string;
  recipientUserId: string | null;
  token: string;
  status: TransferStatus;
  expiresAt: Date;
  createdAt: Date;
  updatedAt: Date;
};

/** Transfer with resolved ticket and sender relations. */
export type TicketTransferWithRelations = TicketTransferRecord & {
  ticket: { id: string; status: string; buyerId: string };
  sender: { id: string; name: string; lastName: string; email: string };
};

// ── Selects ───────────────────────────────────────────────────────────────────

const TRANSFER_WITH_RELATIONS_SELECT = {
  id: true,
  ticketId: true,
  senderId: true,
  recipientEmail: true,
  recipientUserId: true,
  token: true,
  status: true,
  expiresAt: true,
  createdAt: true,
  updatedAt: true,
  ticket: {
    select: {
      id: true,
      status: true,
      buyerId: true,
    },
  },
  sender: {
    select: {
      id: true,
      name: true,
      lastName: true,
      email: true,
    },
  },
} as const;

// ── Repository ────────────────────────────────────────────────────────────────

@Injectable()
export class TicketTransfersRepository {
  constructor(private readonly prisma: PrismaService) {}

  /**
   * Create a new TicketTransfer record.
   * The token is auto-generated by the DB default (uuid()).
   */
  create(data: {
    ticketId: string;
    senderId: string;
    recipientEmail: string;
    expiresAt: Date;
  }): Promise<TicketTransferRecord> {
    return this.prisma.ticketTransfer.create({ data }) as Promise<TicketTransferRecord>;
  }

  /**
   * Find a transfer by ID including ticket and sender relations.
   */
  findById(id: string): Promise<TicketTransferWithRelations | null> {
    return this.prisma.ticketTransfer.findUnique({
      where: { id },
      select: TRANSFER_WITH_RELATIONS_SELECT,
    }) as Promise<TicketTransferWithRelations | null>;
  }

  /**
   * Find a transfer by its unique token including ticket and sender relations.
   */
  findByToken(token: string): Promise<TicketTransferWithRelations | null> {
    return this.prisma.ticketTransfer.findUnique({
      where: { token },
      select: TRANSFER_WITH_RELATIONS_SELECT,
    }) as Promise<TicketTransferWithRelations | null>;
  }

  /**
   * Paginated list of transfers sent by a given user.
   */
  async findBySenderId(
    senderId: string,
    page: number,
    limit: number,
  ): Promise<{ data: TicketTransferRecord[]; total: number }> {
    const [data, total] = await Promise.all([
      this.prisma.ticketTransfer.findMany({
        where: { senderId },
        skip: (page - 1) * limit,
        take: limit,
        orderBy: { createdAt: 'desc' },
      }),
      this.prisma.ticketTransfer.count({ where: { senderId } }),
    ]);
    return { data: data as TicketTransferRecord[], total };
  }

  /**
   * Find an existing PENDING transfer for a ticket (for conflict detection).
   */
  findPendingByTicketId(ticketId: string): Promise<TicketTransferRecord | null> {
    return this.prisma.ticketTransfer.findFirst({
      where: { ticketId, status: TransferStatus.PENDING },
    }) as Promise<TicketTransferRecord | null>;
  }

  /**
   * Update only the status (and optionally the recipientUserId) of a transfer.
   */
  updateStatus(
    id: string,
    status: TransferStatus,
    recipientUserId?: string,
  ): Promise<TicketTransferRecord> {
    return this.prisma.ticketTransfer.update({
      where: { id },
      data: { status, ...(recipientUserId !== undefined ? { recipientUserId } : {}) },
    }) as Promise<TicketTransferRecord>;
  }

  /**
   * Atomically accept a transfer and reassign the ticket to the new owner.
   * Uses an interactive transaction to first resolve the ticketId, then update both records.
   */
  async completeTransfer(transferId: string, newOwnerId: string): Promise<TicketTransferRecord> {
    return this.prisma.$transaction(async (tx) => {
      const transfer = await tx.ticketTransfer.update({
        where: { id: transferId },
        data: { status: TransferStatus.ACCEPTED, recipientUserId: newOwnerId },
      });
      await tx.ticket.update({
        where: { id: transfer.ticketId },
        data: { buyerId: newOwnerId },
      });
      return transfer as TicketTransferRecord;
    });
  }
}
