FROM oven/bun:1-alpine
WORKDIR /app

RUN addgroup --system --gid 1001 nestjs && \
    adduser --system --uid 1001 nestjs

COPY package.json bun.lock ./
RUN bun install

COPY prisma ./prisma
RUN bunx prisma generate --schema=./prisma/schema.prisma

COPY nest-cli.json tsconfig*.json ./
COPY src ./src

RUN chown -R nestjs:nestjs /app

USER nestjs

CMD ["bun", "run", "start:dev"]
