# Stage 1: Instalación de dependencias de desarrollo

FROM oven/bun:1-alpine AS deps
WORKDIR /app
COPY package.json bun.lock ./
RUN bun install --frozen-lockfile

# Stage 2: Instalación de dependencias de producción

FROM oven/bun:1-alpine AS prod-deps
WORKDIR /app
COPY package.json bun.lock ./
RUN bun install --frozen-lockfile --production

# Stage 3: Construcción de la aplicación

FROM oven/bun:1-alpine AS builder
WORKDIR /app

COPY --from=deps /app/node_modules ./node_modules
COPY package.json bun.lock ./
COPY prisma ./prisma
COPY prisma.config.ts ./
COPY nest-cli.json tsconfig*.json ./
COPY src ./src

RUN bunx prisma generate --schema=./prisma/schema.prisma

RUN bun run build

# Stage 4: Ejecución de la aplicación

FROM oven/bun:1-alpine AS runner
WORKDIR /app

RUN addgroup --system --gid 1001 nestjs && \
    adduser --system --uid 1001 nestjs

COPY --from=prod-deps --chown=nestjs:nestjs /app/node_modules ./node_modules
COPY --from=builder --chown=nestjs:nestjs /app/dist ./dist
COPY --from=builder --chown=nestjs:nestjs /app/prisma ./prisma
COPY --from=builder --chown=nestjs:nestjs /app/prisma.config.ts ./prisma.config.ts
COPY --from=builder --chown=nestjs:nestjs /app/src/generated ./src/generated
COPY --from=builder --chown=nestjs:nestjs /app/package.json ./package.json

ENV NODE_ENV=production

USER nestjs

EXPOSE 3001

CMD ["sh", "-c", "bunx prisma migrate deploy && bun dist/main.js"]
